# 文件名修改为config.yaml后生效

bot_name: "机器人名字" 
superuser:  
  - 11111111
  - 22222222


bobing:
  cd: 60         


helper:
  cd: 300  # 每种help查询单独的cd                


chat:
  api_key: "sk-xxxxxxxxx"
  api_base: "https://xxxxxxxxxx/v1"
  proxy: ""
  model_id: "gpt-4-vision-preview"
  fold_response_threshold: 200    # 群聊中超过多少字折叠回复
  session_len_limit: 10           # 会话长度限制
  max_retries: 5                  # 最大重试次数
  retry_interval: 1               # 重试间隔（秒） 
  max_tokens: 2048                # 最大生成长度
  cd: 60                       


mc:
  query_interval: 0.5            # 向卫星地图查询的间隔（秒）
  queue_consume_interval: 1      # 队列消费间隔（秒）
  query_offset: 2000             # 查询时间的偏移量
  group_server_pairs:            # 群组与服务器的对应关系
    - group_id: '111111111'
      url: 'http://卫星地图网址'
  disconnect_notify_count: 3      # 和服务器断联多少次后提醒


pjsk:
  cd: 60                                 

  max_vlive_endtime_diff: 7               # 最多只获取多久之前的vlive（天）
  vlive_update_time: [5, 0, 0]            # vlive数据更新时间 [hour, minute, second]
  vlive_notify_interval_minute: 5         # 每隔多少分钟检查vlive的提醒
  vlive_start_notify_before_minute: 180   # 提前多少分钟提醒vlive开始
  vlive_end_notify_before_minute: 180     # 提前多少分钟提醒vlive结束

  max_event_endtime_diff: 30              # 最多只获取多久之前的event（天）
  event_update_time: [5, 1, 0]            # event数据更新时间 [hour, minute, second]
  event_notify_interval_minute: 5         # 每隔多少分钟检查event的提醒
  event_start_notify_before_minute: 180   # 提前多少分钟提醒event开始
  event_end_notify_before_minute: 180     # 提前多少分钟提醒event结束


record:
  

run_code:
  cd: 60                       


statistics:
  font_path: "/root/.fonts/MicrosoftYaHei/Microsoft Yahei.ttf"  # WordCloud库使用的中文字体路径
  font_name: "Microsoft YaHei"                                  # Matplotlib库使用的中文字体名称
  statistic_time: [23, 45, 00]  # 统计时间 [hour, minute, second]
  name_len_limit: 16            # 用户名长度限制
  pie_topk: 9                   # 饼图显示的前k名
  plot_topk: 5                  # 折线图显示的前k名
  plot_interval: 15             # 折线图的时间间隔（分钟）


water:
  cd: 60                      


welcome:
  check_interval: 10            # 检查间隔（秒）
