bot_name: ""
log_level: "INFO"
superuser:
  - 12345

msg_rate_limit_per_second: 3  # 每秒限制发送消息的数量

cd_verbose_interval: 30 # 冷却中时间隔多少秒输出一次cd信息

font_path: "/root/.fonts/MicrosoftYaHei/Microsoft Yahei.ttf"  # 中文字体路径
font_name: "Microsoft YaHei"                                  # Matplotlib库使用的中文字体名称

exception_mail: # 发送异常消息邮件的配置
  host: "smtp.qq.com"          # 邮箱服务器地址
  port: 587                    # 邮箱服务器端口
  user: "123@qq.com"      # 邮箱发送者用户名
  pass: "abcdefg"     # 邮箱密码
  receivers:                   # 邮箱接收者列表
    - 1234@qq.com


alive:
  check_interval: 3                 # 存活检测间隔（秒）
  time_threshold: 10                # 状态改变多久后才发送提醒（秒）
  notify_at_connect: False          # 恢复连线时是否发送邮件提醒
  notify_at_disconnect: True        # 断线时是否发送邮件提醒
  notify_at_first: False            # 如果bot启动时已经断线/连接，是否发送一次邮件提醒

  report_groups:  # 群聊连线通知
    - 123


bird:
  cd: 3
  folk_name_max: 10                 # 俗名匹配显示的最大数量
  query_topk: 10                    # 模糊查询显示的前k名
  max_edit_distance: 2              # 模糊查询的最大编辑距离
  

bobing:
  cd: 3        


broadcast:
  cd: 3          


helper:
  cd: 3  # 每种help查询单独的cd


imgexp:
  saucenao_apikey: ""
  serp_apikey: ""
  cd: 3


imgtool:
  cd: 3


llm:
  chat_max_tokens: 2048                    # 聊天最大生成长度

  text_embedding_model:                    # 文本嵌入模型
    provider: "AI-YYDS"
    id: "text-embedding-ada-002"           
    input_pricing:  0.00000002             # 每个输入token的价格（美元）

  tts_model:                               # 文本转语音模型
    provider: "AI-YYDS"
    id: "tts-1"
    input_pricing:  0.000015               # 每个输入字符的价格（美元）
    voice: "alloy"                         # TTS语音名称
  

chat:
  default_private_model_name: # 默认私聊模型名称
    text: "gpt-4o"
    mm: "gpt-4o"
    tool: "gpt-4o"
  default_group_model_name:   # 默认群聊模型名称
    text: "deepseek-v3-free"
    mm: "qwen2.5-vl-72b-instruct-free" 
    tool: "gpt-4o"
  fold_response_threshold: 400              # 群聊中超过多少字折叠回复
  session_len_limit: 20                     # 会话长度限制
  chat_cd: 10
  tts_cd: 60
  img_trans_cd: 120


cron:
  model_name: "gpt-4o"            # 使用的模型名称
  max_retries: 5                  # 最大重试次数
  cd: 3  


eval:
  cd: 3


mc:
  query_interval: 1              # 向卫星地图查询的间隔（秒）
  queue_consume_interval: 1      # 队列消费间隔（秒）
  query_offset: -1000            # 查询时间的偏移量
  disconnect_notify_count: 60    # 和服务器断联多少次后提醒
  ascii_art_width: 50            # 字符画的宽度
  player_time_update_interval: 60   # 超过多少秒自动更新玩家在线时间
  cd: 3


oeis:
  search_num: 3
  cd: 3


record:
  cd: 3

rpc:
  host: "0.0.0.0"
  port: 24444
  

run_code:
  cd: 3     


sekai:
  cd: 3               


statistics:
  statistic_time: [23, 50, 00]  # 统计时间 [hour, minute, second]
  name_len_limit: 16            # 用户名长度限制
  pie_topk: 9                   # 饼图显示的前k名
  plot_topk: 5                  # 折线图显示的前k名
  plot_interval: 15             # 折线图的时间间隔（分钟）
  sta_word_topk: 8              # 词汇统计显示前k个用户
  cd: 3


touhou:
  sc_query_max_num: 5           # 符卡查询显示的最大数量
  cd: 3


water:
  cd: 3                      


welcome:
  group_info_update_interval: 30  # 群组信息更新间隔（分钟）


misc:
