# 文件名修改为config.yaml后生效

bot_name: "机器人名字" 
log_level: "DEBUG"
superuser:  
  - 11111111
  - 22222222

font_path: "/root/.fonts/MicrosoftYaHei/Microsoft Yahei.ttf"  # 中文字体路径
font_name: "Microsoft YaHei"                                  # Matplotlib库使用的中文字体名称

openai:
  api_key: "sk-xxxxxxxxx"
  api_base: "https://xxxxxxxxxx/v1"
  proxy: ""


alive:
  check_interval: 3                 # 存活检测间隔（秒）
  time_threshold: 10                # 状态改变多久后才发送提醒（秒）
  notify_at_connect: True           # 恢复连线时是否发送提醒
  notify_at_disconnect: True        # 断线时是否发送提醒
  notify_at_first: False            # 如果bot启动时已经断线/连接，是否发送一次提醒
  send_email: True                  # 是否发送邮件
  mail_host: "smtp.qq.com"          # 邮箱服务器地址
  mail_port: 25                     # 邮箱服务器端口
  mail_user: "xxxxxxxx@qq.com"      # 邮箱发送者用户名
  mail_pass: "xxxxxxxxxxxxxxxx"     # 邮箱密码
  mail_receivers:                   # 邮箱接收者列表
    - "xxxxxxxx@qq.com"


bird:
  cd: 60
  folk_name_max: 10                 # 俗名匹配显示的最大数量
  query_topk: 10                    # 模糊查询显示的前k名
  max_edit_distance: 2              # 模糊查询的最大编辑距离


bobing:
  cd: 60         


helper:
  cd: 300  # 每种help查询单独的cd         


imgexp:
  google_cookies: "HSID=AFAWa6hemvh3Fb41d; SSID=AvU4NRYUm4-qU9BFI; APISID=25jh8eudbwOuyxut/AnPs1Zbgp3Pvkc_pq; SAPISID=1I5b80F32QADupQr/AnI5Ikvh3Pb5pjwsf; __Secure-1PAPISID=1I5b80F32QADupQr/AnI5Ikvh3Pb5pjwsf; __Secure-3PAPISID=1I5b80F32QADupQr/AnI5Ikvh3Pb5pjwsf; SEARCH_SAMESITE=CgQIh5oB; SID=fwgWQheDO_reL5q1m0VdEym5bWQatbqGYkcJERGa6UHIXHHKGP1xKwaOqFRehV3lXXWzDA.; __Secure-1PSID=fwgWQheDO_reL5q1m0VdEym5bWQatbqGYkcJERGa6UHIXHHK8J3SUVM0QAtUn5xQ1QsW5Q.; __Secure-3PSID=fwgWQheDO_reL5q1m0VdEym5bWQatbqGYkcJERGa6UHIXHHKhv0Zo1aM9kRw4H5uXjhayA.; 1P_JAR=2024-02-05-02; NID=511=M-Pwudo35052ROlhUM0bvcOSGyUb0Awjy7h2j5x9yoou3gdU25KrhI_uY_9yGHJQF4HWWLzr7Fja0LydHUpiKluiFmbP22b9Z0hpbadW5lWxvlHPDaU7ib3h9TD-iqJP1rscWHfBMFnTTMYY5ZpffJuEwVXekp1TjLlnswHVHesY8GdclwEXTghBZFABnEeBLMDkqkYPa9OqnJAeVFz29BN2v7AqmjxjyR7KWYFjtpQsfnfRb8YWnlRWWgd_N_EjH2qfO0AuKJrZZdAhCWxV9Ww7pBOe9w7DB_mlSNSj0SPUdrNrVvFoU2EtKAFqJ5qMIdY0U4bWHCaZrr5Be7SgQhFHR4olHPiHFJMn30eCo5lDl9f9bbeT; AEC=Ae3NU9MK1-ecwzOFNrBNSBUj1mtuNAlZvm4d_HhO2gOIU9kf3X25NFV4ag; __Secure-1PSIDTS=sidts-CjABPVxjSkDsRvuoiBUXPZ1YQz65eS5N4QgYhkFKjNnJPjQDP7bsVN8yocR8sq0ZGskQAA; __Secure-3PSIDTS=sidts-CjABPVxjSkDsRvuoiBUXPZ1YQz65eS5N4QgYhkFKjNnJPjQDP7bsVN8yocR8sq0ZGskQAA; OSID=g.a000gAgWQvUpGU5DSdYx772JfdIhMAA7SYx5u41YSHvt0HMgHl4eGPSJAEoNGcTGoaBRl3uI2wACgYKAUYSAQASFQHGX2MidRuduYUoAS5m4xlHePOuoRoVAUF8yKpiDMENDnvUjNJ8IH4oe5cR0076; __Secure-OSID=g.a000gAgWQvUpGU5DSdYx772JfdIhMAA7SYx5u41YSHvt0HMgHl4eY9SwrKX-JlLtTEymXGot9AACgYKASkSAQASFQHGX2MiT9qz37Hd2c4Mb0cLkuZtXxoVAUF8yKoKSN2-ruefiSEaMfkk-DHY0076; OTZ=7413284_24_24__24_; SIDCC=ABTWhQFLFg2BrhvU17TOMhuxb65FH8kqOcpYEPZ7t2mwwUZZCvrws_WJC-G_ogW29gZxm5JMRw8; __Secure-1PSIDCC=ABTWhQF1nlGPJHTBCEdPIho1sF5HfsRtBJdH1Y20bDuNROCebnJoSXew3PefFzptoK3ERNCwLw; __Secure-3PSIDCC=ABTWhQG63H_iA_RZJmfQc1d5B0lN1s4v8liVnoGyg6evkNsCvJDcpHLyZ3s4XcU6tSdBAlHtlg"
  saucenao_apikey: "c9b7e159baa5ec9e7334e81efdaed6213f9a8d55"
  saucenao_max_num: 5
  google_max_num: 5
  yandex_max_num: 0
  ascii2d_max_num: 0
  cd: 60     


chat:
  query_model:                    # 询问使用的模型
    id: "gpt-4-vision-preview"
    input_pricing:  0.00001       # 每个输入token的价格（美元）
    output_pricing: 0.00003       # 每个输出token的价格（美元）
    
  autochat_model:                 # 自动聊天使用的模型
    id: "gpt-3.5-turbo-16k"
    input_pricing:  0.0000005     # 每个输入token的价格（美元）
    output_pricing: 0.0000015     # 每个输出token的价格（美元）

  fold_response_threshold: 200    # 群聊中超过多少字折叠回复
  session_len_limit: 10           # 会话长度限制
  max_retries: 5                  # 最大重试次数
  retry_interval: 1               # 重试间隔（秒） 
  max_tokens: 2048                # 最大生成长度
  auto_chat_prob_start: 0.0050    # 自动聊天的初始概率
  auto_chat_prob_inc:   0.0025    # 自动聊天的概率增加
  auto_chat_recent_limit: 20      # 自动聊天时，提供多少条最近的消息作为参考
  auto_chat_self_limit: 20        # 自动聊天时，提供多少自己的最近发言作为参考
  auto_chat_mimic_limit: 50       # 自动聊天时，提供多少模仿对象的最近发言作为参考
  auto_chat_self_name: ""         # 自动聊天时，自己的名字
  per_user_usage_topk: 9          # 统计使用额度时展示前k名
  cd: 60                                  


mc:
  query_interval: 0.5            # 向卫星地图查询的间隔（秒）
  queue_consume_interval: 1      # 队列消费间隔（秒）
  query_offset: 2000             # 查询时间的偏移量
  disconnect_notify_count: 3      # 和服务器断联多少次后提醒
  ascii_art_width: 20            # 字符画的宽度
  cd: 5


pjsk:
  cd: 60                                 

  max_vlive_endtime_diff: 7               # 最多只获取多久之前的vlive（天）
  vlive_update_time: [5, 0, 0]            # vlive数据更新时间 [hour, minute, second]
  vlive_notify_interval_minute: 1         # 每隔多少分钟检查vlive的提醒
  vlive_start_notify_before_minute:       # 提前多少分钟提醒vlive开始（列表）
    - 180
    - 10
  vlive_end_notify_before_minute:         # 提前多少分钟提醒vlive结束（列表）
    - 180
    - 10

  max_event_endtime_diff: 30              # 最多只获取多久之前的event（天）
  event_update_time: [5, 1, 0]            # event数据更新时间 [hour, minute, second]
  event_notify_interval_minute: 1         # 每隔多少分钟检查event的提醒
  event_start_notify_before_minute:       # 提前多少分钟提醒event开始 （列表）
    - 180
    - 10
  event_end_notify_before_minute:         # 提前多少分钟提醒event结束（列表）
    - 180
    - 10


record:
  

run_code:
  cd: 60                       


statistics:
  statistic_time: [23, 45, 00]  # 统计时间 [hour, minute, second]
  name_len_limit: 16            # 用户名长度限制
  pie_topk: 9                   # 饼图显示的前k名
  plot_topk: 5                  # 折线图显示的前k名
  plot_interval: 15             # 折线图的时间间隔（分钟）

touhou:
  model_id: "text-embedding-ada-002"  
  sc_query_max_num: 5           # 符卡查询显示的最大数量
  cd: 60

water:
  cd: 60                      


welcome:
  group_info_update_interval: 30  # 群组信息更新间隔（分钟）
